name: rykr
favicon: null
layout_spectrum: 0.20625681383535266
typography_spectrum: 0.9673917714972049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.932107558241114
  lightness: 0.5035796007141471
  saturation: 0.004674130119383335
  rhythmicContrast: 0.46051914151757956
purpose: []
